version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
    links:
      - postgres:postgres
      - rabbitmq:rabbitmq

  postgres:
      image: postgres:latest
      environment:
        POSTGRES_DB: python_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672" 
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: 123456
